# Generated by Django 2.2.24 on 2021-12-15 19:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0008_auto_20211215_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 19, 26, 48, 343601, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
